import { ThemeProvider } from '@/components/theme-provider'
import '@/styles/globals.css'
import { Toaster } from '@/components/ui/sonner'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'
import NextTopLoader from 'nextjs-toploader'
import ClientProviders from '@/components/clientProviders'

export const metadata: Metadata = {
  title: 'Nodez Block Chain - Truly One Click Node Running Services',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader
            color="#D3FF54"
            template='<div class="bar" role="bar"><div class="peg"></div></div>'
          />
          <ClientProviders>
            {children}
          </ClientProviders>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
